### PR TITLE
Drafting 1st version

### PR DESCRIPTION
**Pull request by TermeHansen**
1st try at making this new addon

### CODE REVIEW

**Comment by TermeHansen** [comment]
I just updated with a new subtitles (bool) setting for `play_channel`, and made a trial version of `play_latest`. Right now the `play_latest` will search on the `program_name` and take the 1st match, and if a season it will find the latest in that tv-show.

I tried a few random and they work, but please test this function a bit more. Also I forwarded the title and image, but I don't think the will work on my player. Do you see the title and image, or is it only if I make something with this service in HA maybe?

**Comment by agdamsbo** [comment]
Great! I am away from home this weekend, but I will give it a thorough run when home.

**Comment by agdamsbo** [comment]
`play_channel` works for all four channels streaming to a dlna renderer (my television). Subtitles also working. Sound and everything. Really nice!

using `play_program`, I can start a stream, but no sound is coming through.  The stream quality is also lower than `play_channel` I think. Choosing the programme "Alene i Vildmarken" will start streaming "Alene i Vildmarken USA".

I have tried both series and programmes, and everything starts quick, but no sound. is there a log to share?

**Comment by TermeHansen** [comment]
I saw in svt play they had option for hls or dash type stream. I will see if I can make a config option for you to to test on quality.

On the play_latest for specific show I understand what happens and will use that example as test for better program_name use... I'll post when I have something

**Comment by TermeHansen** [comment]
Alright added now option to pass the path from drtv or the id, to make sure which show to find latest from.
We are using the same api as the homepage dr.dk, and as you can see here:
image

is the first item for that search (Alene i vildmarken) giving the USA version for some reason...
So now I added that one can pass either the last part of the path or simply the id. see the two new test below.

https://github.com/TermeHansen/home-assistant-drtv-play/blob/69e97471b9b8c196c73236e10fb8d49d441d7316/custom_components/drtv_play/video_url_fetch/live_test.py#L32-L33

For the stream quality I am not sure what I can do. dr.dk only gives the hls streams and I ask for the 1080P version (like my browser do, I have reversed engineered from what my browser do), and in kodi it plays fine that 1080P stream...

**Comment by agdamsbo** [comment]
I am also able to get the correct link through the [svtplay-dl](https://svtplay-dl.se/) program. I will have a look at it tonight. 

Do you have a clear idea if it should be added through HACS or as a custom add-on? As I understand, the repository could be added through HACS by adding a `hacs.json` in the root? That would make testing easier, now that the basics are working. I created it here ca4837d2d42faead9074c5946052bc4d4c2850bd, though it will be a comically small contribution.

**Comment by agdamsbo** [comment]
Added a basic README mostly copy-pasted from [lindell/home-assistant-svt-play](https://github.com/lindell/home-assistant-svt-play), 30eb62ae0320528167d43103a4cbbd1bb1b00a77.

Should I create a PR for these two additions?

**Comment by TermeHansen** [comment]
@agdamsbo Hangon, I'll push this PR in then as a working 1st draft. Then you can have your PR with documentation and steps towards HACS

**Pull request merged**
